version: "3.7"
services:
  node-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: holiday-node-app
    image: holiday-node-app:1.0.0
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/home/node_app/src
    ports:
      - 3000:3000
    command: ["sh", "-c", "npm run build && npm run dev"]
      
  postgres:
    image: postgres:14-alpine
    container_name: postgres14-db
    env_file:
      - .env
    ports:
      - 6000:5432
    volumes:
      - pg14_data:/var/lib/postgresql/data/

volumes:
  pg14_data:
